name: Build GoGo

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch: # From TUT

jobs:
  build-server:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    defaults:
      run:
        working-directory: setup/server
    
    steps:
    - uses: actions/checkout@v2 # Needed by default

    - name: Build server image
      run: docker build . --file Dockerfile --tag perfectstrangers/setup-server:v1.0.1
      
    - name: Log into DockerHub Registry xx
      run: echo "perfect-strangers" | docker login -u perfectstrangers --password-stdin 

    - name: Push server image to DockerHub Registry
      run: docker push perfectstrangers/setup-server:v1.0.1
  
  build-client:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [18.x]

    defaults:
      run:
        working-directory: setup/client
    
    steps:
    - uses: actions/checkout@v2 # Needed by default
    
    - name: Install node_modules
      run: npm i
      
    # - name: Run unit tests
    #   run: npm test

    - name: Build client image
      run: docker build . --file Dockerfile --tag perfectstrangers/setup-client:v1.0.1

    - name: Log into DockerHub Registry
      run: echo "perfect-strangers" | docker login -u perfectstrangers --password-stdin 

    - name: Push server image to DockerHub Registry
      run: docker push perfectstrangers/setup-client:v1.0.1
